def  appName = "my-node-app"
pipeline {
  agent none
  stages {
    stage('Develpment') {
      when { branch 'development' }
      steps {
        echo "Starting development deploy ...."
      }
    }
    stage('Test') {
      steps {
        echo "Starting development deploy ...."

      }
    }
    stage('staging') {
      when { branch 'staging' }
      steps {
        echo "Starting development deploy ...."
      }
    }
    stage('Master') {
      agent any
      when { branch 'master' }
      steps {
        echo "Starting master deploy ...."
        sh ("gcloud app deploy --version='my-node-app' --no-promote app.yaml")
      }
    }
  }
}